export const languages: Record<string, string> = {
	'Afaan Oromoo': 'om',
	Afaraf: 'aa',
	Afrikaans: 'af',
	Akan: 'ak',
	aragonés: 'an',
	'Asụsụ Igbo': 'ig',
	"Avañe'ẽ": 'gn',
	avesta: 'ae',
	'aymar aru': 'ay',
	'azərbaycan dili': 'az',
	'Bahasa Indonesia': 'id',
	'Bahasa Melayu': 'ms',
	bamanankan: 'bm',
	'basa Jawa': 'jv',
	'Basa Sunda': 'su',
	Bislama: 'bi',
	'bosanski jezik': 'bs',
	brezhoneg: 'br',
	Català: 'ca',
	čeština: 'cs',
	Chamoru: 'ch',
	chiCheŵa: 'ny',
	chiShona: 'sn',
	corsu: 'co',
	Cymraeg: 'cy',
	dansk: 'da',
	Davvisámegiella: 'se',
	Deutsch: 'de',
	'Diné bizaad': 'nv',
	'Dorerin Naoero': 'na',
	eesti: 'et',
	English: 'en',
	Español: 'es',
	Esperanto: 'eo',
	euskara: 'eu',
	Eʋegbe: 'ee',
	'faka Tonga': 'to',
	'fiteny malagasy': 'mg',
	føroyskt: 'fo',
	Français: 'fr',
	Frysk: 'fy',
	Fulfulde: 'ff',
	Gaeilge: 'ga',
	Gaelg: 'gv',
	"gagana fa'a Samoa": 'sm',
	Gàidhlig: 'gd',
	galego: 'gl',
	Gĩkũyũ: 'ki',
	'Hiri Motu': 'ho',
	Hrvatski: 'hr',
	Ido: 'io',
	Ikinyarwanda: 'rw',
	Ikirundi: 'rn',
	Interlingua: 'ia',
	Interlingue: 'ie',
	Iñupiaq: 'ik',
	isiNdebele: 'nd',
	isiXhosa: 'xh',
	isiZulu: 'zu',
	Íslenska: 'is',
	Italiano: 'it',
	'Kajin M̧ajeļ': 'mh',
	kalaallisut: 'kl',
	Kanuri: 'kr',
	Kernewek: 'kw',
	Kikongo: 'kg',
	Kiluba: 'lu',
	Kiswahili: 'sw',
	'Kreyòl ayisyen': 'ht',
	Kuanyama: 'kj',
	Kurdî: 'ku',
	latine: 'la',
	'latviešu valoda': 'lv',
	Lëtzebuergesch: 'lb',
	'lietuvių kalba': 'lt',
	Limburgs: 'li',
	Lingála: 'ln',
	Luganda: 'lg',
	magyar: 'hu',
	Malti: 'mt',
	Nederlands: 'nl',
	Norsk: 'no',
	'Norsk bokmål': 'nb',
	'Norsk nynorsk': 'nn',
	occitan: 'oc',
	Otjiherero: 'hz',
	Owambo: 'ng',
	Polski: 'pl',
	Português: 'pt',
	'Reo Tahiti': 'ty',
	Română: 'ro',
	'rumantsch grischun': 'rm',
	'Runa Simi': 'qu',
	sardu: 'sc',
	'Saɯ cueŋƅ': 'za',
	Sesotho: 'st',
	Setswana: 'tn',
	Shqip: 'sq',
	SiSwati: 'ss',
	slovenčina: 'sk',
	slovenščina: 'sl',
	Soomaaliga: 'so',
	suomi: 'fi',
	Svenska: 'sv',
	'te reo Māori': 'mi',
	'Tiếng Việt': 'vi',
	Tshivenḓa: 've',
	Türkçe: 'tr',
	Türkmençe: 'tk',
	Twi: 'tw',
	Volapük: 'vo',
	'vosa Vakaviti': 'fj',
	walon: 'wa',
	'Wikang Tagalog': 'tl',
	Wollof: 'wo',
	Xitsonga: 'ts',
	'yângâ tî sängö': 'sg',
	Yorùbá: 'yo',
	Ελληνικά: 'el',
	'авар мацӀ': 'av',
	'аҧсуа бызшәа': 'ab',
	'башҡорт теле': 'ba',
	'беларуская мова': 'be',
	'български език': 'bg',
	'ирон æвзаг': 'os',
	'коми кыв': 'kv',
	Кыргызча: 'ky',
	'қазақ тілі': 'kk',
	'македонски јазик': 'mk',
	'Монгол хэл': 'mn',
	'нохчийн мотт': 'ce',
	Русский: 'ru',
	'српски језик': 'sr',
	'татар теле': 'tt',
	тоҷикӣ: 'tg',
	Ўзбек: 'uz',
	Українська: 'uk',
	'чӑваш чӗлхи': 'cv',
	'ѩзыкъ словѣньскъ': 'cu',
	ქართული: 'ka',
	Հայերեն: 'hy',
	ייִדיש: 'yi',
	עברית: 'he',
	'ئۇيغۇرچە‎': 'ug',
	اردو: 'ur',
	اَلْعَرَبِيَّةُ: 'ar',
	پښتو: 'ps',
	فارسی: 'fa',
	هَوُسَ: 'ha',
	ދިވެހި: 'dv',
	ትግርኛ: 'ti',
	አማርኛ: 'am',
	कश्मीरी: 'ks',
	नेपाली: 'ne',
	पाऴि: 'pi',
	मराठी: 'mr',
	संस्कृतम्: 'sa',
	सिन्धी: 'sd',
	हिन्दी: 'hi',
	অসমীয়া: 'as',
	বাংলা: 'bn',
	ਪੰਜਾਬੀ: 'pa',
	ગુજરાતી: 'gu',
	ଓଡ଼ିଆ: 'or',
	தமிழ்: 'ta',
	తెలుగు: 'te',
	ಕನ್ನಡ: 'kn',
	മലയാളം: 'ml',
	සිංහල: 'si',
	ไทย: 'th',
	ພາສາລາວ: 'lo',
	'བོད་ཡིག': 'bo',
	'རྫོང་ཁ': 'dz',
	ဗမာစာ: 'my',
	ខេមរភាសា: 'km',
	ᐃᓄᒃᑎᑐᑦ: 'iu',
	ᐊᓂᔑᓈᐯᒧᐎᓐ: 'oj',
	ᓀᐦᐃᔭᐍᐏᐣ: 'cr',
	한국어: 'ko',
	'ꆈꌠ꒿ Nuosuhxop': 'ii',
	中文: 'zh',
	日本語: 'ja',
};
